/*
 * Content for the site. Scripture is quoted from the King James Version (public domain).
 * Encounter order follows a traditional harmony of the four Gospels.
 */

window.SITE = {
  name: "Behold",
  tagline: "The life of Jesus Christ, told through every soul He touched.",
  dedication: "Made with love, for my mother."
};

window.VERSES = [
  { t: "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.", r: "John 3:16" },
  { t: "Come unto me, all ye that labour and are heavy laden, and I will give you rest.", r: "Matthew 11:28" },
  { t: "Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid.", r: "John 14:27" },
  { t: "The LORD is my shepherd; I shall not want.", r: "Psalm 23:1" },
  { t: "Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me.", r: "Psalm 23:4" },
  { t: "But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.", r: "Isaiah 40:31" },
  { t: "Trust in the LORD with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths.", r: "Proverbs 3:5–6" },
  { t: "And we know that all things work together for good to them that love God, to them who are the called according to his purpose.", r: "Romans 8:28" },
  { t: "For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end.", r: "Jeremiah 29:11" },
  { t: "I can do all things through Christ which strengtheneth me.", r: "Philippians 4:13" },
  { t: "Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest.", r: "Joshua 1:9" },
  { t: "Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness.", r: "Isaiah 41:10" },
  { t: "Be still, and know that I am God.", r: "Psalm 46:10" },
  { t: "It is of the LORD’s mercies that we are not consumed, because his compassions fail not. They are new every morning: great is thy faithfulness.", r: "Lamentations 3:22–23" },
  { t: "We love him, because he first loved us.", r: "1 John 4:19" },
  { t: "I am the light of the world: he that followeth me shall not walk in darkness, but shall have the light of life.", r: "John 8:12" },
  { t: "I am the resurrection, and the life: he that believeth in me, though he were dead, yet shall he live.", r: "John 11:25" },
  { t: "I am the way, the truth, and the life: no man cometh unto the Father, but by me.", r: "John 14:6" },
  { t: "Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven.", r: "Matthew 5:16" },
  { t: "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.", r: "Matthew 6:33" },
  { t: "Lo, I am with you alway, even unto the end of the world.", r: "Matthew 28:20" },
  { t: "But God commendeth his love toward us, in that, while we were yet sinners, Christ died for us.", r: "Romans 5:8" },
  { t: "Neither death, nor life, nor angels, nor principalities, nor powers, nor things present, nor things to come, nor height, nor depth, nor any other creature, shall be able to separate us from the love of God, which is in Christ Jesus our Lord.", r: "Romans 8:38–39" },
  { t: "Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new.", r: "2 Corinthians 5:17" },
  { t: "For by grace are ye saved through faith; and that not of yourselves: it is the gift of God.", r: "Ephesians 2:8" },
  { t: "Now faith is the substance of things hoped for, the evidence of things not seen.", r: "Hebrews 11:1" },
  { t: "Jesus Christ the same yesterday, and to day, and for ever.", r: "Hebrews 13:8" },
  { t: "Thy word is a lamp unto my feet, and a light unto my path.", r: "Psalm 119:105" },
  { t: "The LORD is my light and my salvation; whom shall I fear? the LORD is the strength of my life; of whom shall I be afraid?", r: "Psalm 27:1" },
  { t: "The LORD is nigh unto them that are of a broken heart; and saveth such as be of a contrite spirit.", r: "Psalm 34:18" },
  { t: "He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty.", r: "Psalm 91:1" },
  { t: "For unto us a child is born, unto us a son is given: and his name shall be called Wonderful, Counsellor, The mighty God, The everlasting Father, The Prince of Peace.", r: "Isaiah 9:6" },
  { t: "And God shall wipe away all tears from their eyes; and there shall be no more death, neither sorrow, nor crying, neither shall there be any more pain.", r: "Revelation 21:4" },
  { t: "Behold, I make all things new.", r: "Revelation 21:5" },
  { t: "Behold, I stand at the door, and knock: if any man hear my voice, and open the door, I will come in to him, and will sup with him, and he with me.", r: "Revelation 3:20" },
  { t: "The LORD thy God in the midst of thee is mighty; he will save, he will rejoice over thee with joy; he will rest in his love, he will joy over thee with singing.", r: "Zephaniah 3:17" },
  { t: "The LORD bless thee, and keep thee: the LORD make his face shine upon thee, and be gracious unto thee: the LORD lift up his countenance upon thee, and give thee peace.", r: "Numbers 6:24–26" },
  { t: "Casting all your care upon him; for he careth for you.", r: "1 Peter 5:7" },
  { t: "And the light shineth in darkness; and the darkness comprehended it not.", r: "John 1:5" },
  { t: "Greater love hath no man than this, that a man lay down his life for his friends.", r: "John 15:13" },
  { t: "With men this is impossible; but with God all things are possible.", r: "Matthew 19:26" },
  { t: "Be strong and of a good courage, fear not: for the LORD thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee.", r: "Deuteronomy 31:6" },
  { t: "And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.", r: "Philippians 4:7" },
  { t: "He hath shewed thee, O man, what is good; and what doth the LORD require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?", r: "Micah 6:8" },
  { t: "But he was wounded for our transgressions, he was bruised for our iniquities: the chastisement of our peace was upon him; and with his stripes we are healed.", r: "Isaiah 53:5" },
  { t: "I will both lay me down in peace, and sleep: for thou, LORD, only makest me dwell in safety.", r: "Psalm 4:8" },
  { t: "This is the day which the LORD hath made; we will rejoice and be glad in it.", r: "Psalm 118:24" }
];

window.GOSPELS = [
  {
    key: "mt", name: "Matthew", letter: "M", symbol: "The Winged Man",
    portrait: "The Promised King",
    who: "A tax collector called from his booth in Capernaum.",
    audience: "Written for a Jewish audience, it shows Jesus as the Messiah foretold by the prophets — the Son of David, the true King of Israel.",
    chapters: 28, mark: "Fulfilment of prophecy",
    open: { t: "The book of the generation of Jesus Christ, the son of David, the son of Abraham.", r: "Matthew 1:1" }
  },
  {
    key: "mk", name: "Mark", letter: "M", symbol: "The Lion",
    portrait: "The Suffering Servant",
    who: "John Mark, companion of Peter, recording the apostle’s preaching.",
    audience: "The shortest and swiftest Gospel. Its favourite word is “straightway” — a life of urgent action, poured out in service.",
    chapters: 16, mark: "Action and urgency",
    open: { t: "The beginning of the gospel of Jesus Christ, the Son of God.", r: "Mark 1:1" }
  },
  {
    key: "lk", name: "Luke", letter: "L", symbol: "The Ox",
    portrait: "The Saviour of All",
    who: "A physician and careful historian, travelling companion of Paul.",
    audience: "The most detailed account, with a tender eye for the poor, for women, for outsiders — the Son of Man who came to seek the lost.",
    chapters: 24, mark: "Compassion for the outcast",
    open: { t: "That thou mightest know the certainty of those things, wherein thou hast been instructed.", r: "Luke 1:4" }
  },
  {
    key: "jn", name: "John", letter: "J", symbol: "The Eagle",
    portrait: "The Son of God",
    who: "“The disciple whom Jesus loved,” fisherman and eyewitness.",
    audience: "Soaring like its eagle, it begins before time itself. Seven signs and seven “I AM” sayings reveal the Word made flesh.",
    chapters: 21, mark: "Seven signs, seven “I AM”s",
    open: { t: "In the beginning was the Word, and the Word was with God, and the Word was God.", r: "John 1:1" }
  }
];

window.ACTS = [
  { num: "I", title: "The Word Became Flesh", places: "Nazareth · Bethlehem · Jerusalem", era: "c. 6–4 BC", img: "shepherds",
    verse: { t: "And the Word was made flesh, and dwelt among us, full of grace and truth.", r: "John 1:14" } },
  { num: "II", title: "Prepare the Way", places: "The Jordan · The Wilderness · Bethabara", era: "c. AD 26", img: "baptism",
    verse: { t: "Prepare ye the way of the Lord, make his paths straight.", r: "Mark 1:3" } },
  { num: "III", title: "The First Signs", places: "Cana · Jerusalem · Samaria", era: "c. AD 27", img: "veronese-cana", pos: "50% 60%",
    verse: { t: "This beginning of miracles did Jesus in Cana of Galilee, and manifested forth his glory; and his disciples believed on him.", r: "John 2:11" } },
  { num: "IV", title: "The Kingdom Is at Hand", places: "Nazareth · Capernaum · The Sea of Galilee", era: "c. AD 28", img: "sermon",
    verse: { t: "The time is fulfilled, and the kingdom of God is at hand: repent ye, and believe the gospel.", r: "Mark 1:15" } },
  { num: "V", title: "Bread from Heaven", places: "Bethsaida · Tyre & Sidon · Caesarea Philippi", era: "c. AD 29", img: "transfig", pos: "50% 22%",
    verse: { t: "I am the bread of life: he that cometh to me shall never hunger; and he that believeth on me shall never thirst.", r: "John 6:35" } },
  { num: "VI", title: "The Road to Jerusalem", places: "Judea · Perea · Bethany · Jericho", era: "c. AD 29–30", img: "richruler",
    verse: { t: "He stedfastly set his face to go to Jerusalem.", r: "Luke 9:51" } },
  { num: "VII", title: "Behold, Thy King", places: "Bethany · The Temple · The Upper Room", era: "Passion Week", img: "supper",
    verse: { t: "Fear not, daughter of Sion: behold, thy King cometh, sitting on an ass’s colt.", r: "John 12:15" } },
  { num: "VIII", title: "The Passion", places: "Gethsemane · The Praetorium · Golgotha", era: "Friday", img: "eccehomo", pos: "22% 45%", theme: "passion",
    verse: { t: "But he was wounded for our transgressions, he was bruised for our iniquities: the chastisement of our peace was upon him; and with his stripes we are healed.", r: "Isaiah 53:5" } },
  { num: "IX", title: "He Is Risen", places: "The Garden Tomb · Emmaus · Galilee · Olivet", era: "The First Day of the Week", img: "running", theme: "light",
    verse: { t: "He is not here: for he is risen, as he said. Come, see the place where the Lord lay.", r: "Matthew 28:6" } }
];

/*
 * type: "healing" (incl. deliverance), "miracle" (nature, provision, raising the dead),
 *       "encounter", "teaching"
 * refs: [gospel, reference]
 */
window.ENCOUNTERS = [
  // ── ACT I ─────────────────────────────────────────────
  { id: "zechariah", act: 0, name: "Zechariah", role: "An aged priest of the course of Abijah", type: "encounter", place: "The Temple, Jerusalem",
    refs: [["lk", "1:5–25, 57–80"]],
    text: "While burning incense in the holy place, the old priest is met by the angel Gabriel: his barren wife Elizabeth will bear a son who will prepare the way of the Lord. Doubting, Zechariah is struck silent until the day his son is named John.",
    quote: "Fear not, Zacharias: for thy prayer is heard.", qref: "Luke 1:13" },
  { id: "mary", act: 0, name: "Mary of Nazareth", role: "A young virgin betrothed to Joseph", type: "encounter", place: "Nazareth", img: "annunciation", feature: true,
    refs: [["lk", "1:26–38"], ["mt", "1:18"]],
    text: "Gabriel greets a young woman in an obscure Galilean village: she will conceive by the Holy Spirit and bear the Son of the Highest, whose kingdom shall have no end. Her answer is the most complete surrender in Scripture.",
    quote: "Behold the handmaid of the Lord; be it unto me according to thy word.", qref: "Luke 1:38" },
  { id: "elizabeth", act: 0, name: "Elizabeth", role: "Mary’s kinswoman, mother of John", type: "encounter", place: "Hill country of Judea",
    refs: [["lk", "1:39–56"]],
    text: "When Mary enters her home, the child in Elizabeth’s womb leaps for joy, and she is filled with the Holy Spirit. Mary responds with the Magnificat — “My soul doth magnify the Lord.”",
    quote: "Blessed art thou among women, and blessed is the fruit of thy womb.", qref: "Luke 1:42" },
  { id: "joseph", act: 0, name: "Joseph", role: "A carpenter, son of David", type: "encounter", place: "Nazareth",
    refs: [["mt", "1:18–25"]],
    text: "A just man, Joseph resolves to quietly set Mary aside — until an angel speaks to him in a dream. He rises and obeys, taking Mary as his wife and giving the child His name.",
    quote: "Thou shalt call his name JESUS: for he shall save his people from their sins.", qref: "Matthew 1:21" },
  { id: "shepherds", act: 0, name: "The Shepherds", role: "Keeping watch over their flock by night", type: "encounter", place: "Fields of Bethlehem", img: "shepherds", feature: true,
    refs: [["lk", "2:8–20"]],
    text: "The first to hear the news are not kings but labourers in the dark. The glory of the Lord shines round about them, a multitude of heavenly host sings, and they hurry to find the baby lying in a manger.",
    quote: "For unto you is born this day in the city of David a Saviour, which is Christ the Lord.", qref: "Luke 2:11" },
  { id: "simeon", act: 0, name: "Simeon", role: "A just and devout man awaiting Israel’s consolation", type: "encounter", place: "The Temple, Jerusalem",
    refs: [["lk", "2:25–35"]],
    text: "Promised by the Holy Spirit that he would not die before seeing the Lord’s Christ, Simeon takes the forty-day-old infant in his arms — and warns Mary that a sword will pierce her own soul.",
    quote: "Lord, now lettest thou thy servant depart in peace, according to thy word: for mine eyes have seen thy salvation.", qref: "Luke 2:29–30" },
  { id: "anna", act: 0, name: "Anna", role: "A prophetess of eighty-four years", type: "encounter", place: "The Temple, Jerusalem",
    refs: [["lk", "2:36–38"]],
    text: "A widow who never left the temple, serving God with fasting and prayer night and day. Seeing the child, she gives thanks and speaks of Him to everyone looking for redemption.",
    quote: "She… spake of him to all them that looked for redemption in Jerusalem.", qref: "Luke 2:38" },
  { id: "magi", act: 0, name: "The Magi", role: "Wise men from the East", type: "encounter", place: "Bethlehem", img: "magi", feature: true,
    refs: [["mt", "2:1–12"]],
    text: "Guided by a star, scholars from a distant land travel to worship a child-king. They fall down before Him and open their treasures — gold, frankincense and myrrh — then, warned in a dream, return home another way.",
    quote: "We have seen his star in the east, and are come to worship him.", qref: "Matthew 2:2" },
  { id: "herod", act: 0, name: "Herod the Great", role: "King of Judea", type: "encounter", place: "Jerusalem · Bethlehem",
    refs: [["mt", "2:13–23"]],
    text: "Threatened by news of a newborn King, Herod orders the slaughter of Bethlehem’s infants. Warned by an angel, Joseph flees by night with Mary and the child into Egypt, returning to Nazareth only after Herod’s death.",
    quote: "Out of Egypt have I called my son.", qref: "Matthew 2:15" },
  { id: "teachers", act: 0, name: "The Teachers in the Temple", role: "Doctors of the Law", type: "encounter", place: "The Temple, Jerusalem",
    refs: [["lk", "2:41–52"]],
    text: "At twelve years old, Jesus stays behind after Passover. After three days of searching, Mary and Joseph find Him sitting among the teachers, listening and asking questions — all astonished at His understanding.",
    quote: "Wist ye not that I must be about my Father’s business?", qref: "Luke 2:49" },

  // ── ACT II ────────────────────────────────────────────
  { id: "john-baptist", act: 1, name: "John the Baptist", role: "The voice crying in the wilderness", type: "encounter", place: "The River Jordan", img: "baptism", feature: true,
    refs: [["mt", "3:1–17"], ["mk", "1:1–11"], ["lk", "3:1–22"], ["jn", "1:19–34"]],
    text: "Clothed in camel’s hair, John calls Israel to repentance. When Jesus comes to be baptised, the heavens open, the Spirit descends like a dove, and a voice declares Him the beloved Son. Days later John points to Him and says the words that change everything.",
    quote: "Behold the Lamb of God, which taketh away the sin of the world.", qref: "John 1:29" },
  { id: "tempter", act: 1, name: "The Tempter", role: "The adversary in the wilderness", type: "encounter", place: "The Judean Wilderness", img: "desert", feature: true,
    refs: [["mt", "4:1–11"], ["mk", "1:12–13"], ["lk", "4:1–13"]],
    text: "After forty days of fasting, Jesus is tempted three times — to turn stones to bread, to throw Himself from the temple, to bow for the kingdoms of the world. Each time He answers with the Word of God, and angels come to minister to Him.",
    quote: "Man shall not live by bread alone, but by every word that proceedeth out of the mouth of God.", qref: "Matthew 4:4" },
  { id: "andrew", act: 1, name: "Andrew & John", role: "Disciples of John the Baptist", type: "encounter", place: "Bethabara beyond Jordan",
    refs: [["jn", "1:35–40"]],
    text: "Hearing John call Jesus the Lamb of God, two of his disciples follow Him. Jesus turns and asks what they seek. They spend the day with Him — and Andrew runs to find his brother.",
    quote: "Come and see.", qref: "John 1:39" },
  { id: "peter", act: 1, name: "Simon Peter", role: "A fisherman, brother of Andrew", type: "encounter", place: "Bethabara beyond Jordan",
    refs: [["jn", "1:41–42"]],
    text: "Andrew tells Simon, “We have found the Messias.” Jesus looks at him and gives him a new name — Cephas, the Rock — long before Simon is anything like a rock.",
    quote: "Thou art Simon the son of Jona: thou shalt be called Cephas.", qref: "John 1:42" },
  { id: "philip", act: 1, name: "Philip", role: "Of Bethsaida, the city of Andrew and Peter", type: "encounter", place: "Galilee",
    refs: [["jn", "1:43–44"]],
    text: "The first disciple Jesus seeks out Himself, with two simple words. Philip immediately goes to find his friend.",
    quote: "Follow me.", qref: "John 1:43" },
  { id: "nathanael", act: 1, name: "Nathanael", role: "Of Cana in Galilee", type: "encounter", place: "Galilee",
    refs: [["jn", "1:45–51"]],
    text: "Sceptical — “Can there any good thing come out of Nazareth?” — Nathanael is undone when Jesus reveals He saw him under the fig tree before Philip called him.",
    quote: "Behold an Israelite indeed, in whom is no guile!", qref: "John 1:47" },

  // ── ACT III ───────────────────────────────────────────
  { id: "cana", act: 2, name: "The Servants at Cana", role: "And Mary, His mother", type: "miracle", place: "Cana of Galilee", img: "cana", feature: true,
    refs: [["jn", "2:1–11"]],
    text: "At a wedding feast the wine runs out. Mary turns to the servants with the last recorded words she speaks in Scripture. Six stone jars are filled with water — and drawn out as the finest wine. His first sign.",
    quote: "Whatsoever he saith unto you, do it.", qref: "John 2:5" },
  { id: "moneychangers-1", act: 2, name: "The Money Changers", role: "Merchants in the temple courts", type: "encounter", place: "The Temple, Jerusalem",
    refs: [["jn", "2:13–22"]],
    text: "At Passover, Jesus makes a scourge of small cords and drives out the sellers of oxen, sheep and doves, overturning the changers’ tables. Asked for a sign, He speaks of the temple of His body.",
    quote: "Destroy this temple, and in three days I will raise it up.", qref: "John 2:19" },
  { id: "nicodemus", act: 2, name: "Nicodemus", role: "A Pharisee, a ruler of the Jews", type: "teaching", place: "Jerusalem, by night", img: "nicodemus", feature: true,
    refs: [["jn", "3:1–21"]],
    text: "A respected teacher comes to Jesus under cover of darkness and hears that a man must be born again. In that quiet conversation, Jesus speaks the most beloved sentence in all of Scripture.",
    quote: "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.", qref: "John 3:16" },
  { id: "samaritan-woman", act: 2, name: "The Woman at the Well", role: "A Samaritan with five husbands behind her", type: "encounter", place: "Jacob’s Well, Sychar", img: "well", feature: true,
    refs: [["jn", "4:1–42"]],
    text: "At noon, alone, she comes to draw water — and a Jewish rabbi asks her for a drink. He knows everything she has ever done, and offers her living water. She leaves her waterpot and runs to tell the whole town.",
    quote: "Whosoever drinketh of the water that I shall give him shall never thirst.", qref: "John 4:14" },
  { id: "nobleman", act: 2, name: "The Royal Official", role: "A nobleman whose son lay dying", type: "healing", place: "Cana → Capernaum",
    refs: [["jn", "4:46–54"]],
    text: "He walks twenty miles to beg Jesus to come before his son dies. Jesus sends him home with a word. On the road his servants meet him: the fever left at the very hour Jesus spoke.",
    quote: "Go thy way; thy son liveth.", qref: "John 4:50" },

  // ── ACT IV ────────────────────────────────────────────
  { id: "nazareth", act: 3, name: "The People of Nazareth", role: "His hometown synagogue", type: "teaching", place: "Nazareth",
    refs: [["lk", "4:16–30"], ["mt", "13:54–58"], ["mk", "6:1–6"]],
    text: "Handed the scroll of Isaiah, Jesus reads and declares, “This day is this scripture fulfilled in your ears.” Wonder turns to fury; they drive Him to the brow of a hill — but He passes through the midst of them.",
    quote: "The Spirit of the Lord is upon me, because he hath anointed me to preach the gospel to the poor.", qref: "Luke 4:18" },
  { id: "fishermen", act: 3, name: "Peter, Andrew, James & John", role: "Fishermen of Galilee", type: "miracle", place: "Lake of Gennesaret", img: "fishes", feature: true,
    refs: [["lk", "5:1–11"], ["mt", "4:18–22"], ["mk", "1:16–20"]],
    text: "After a night of catching nothing, Peter lets down the nets at Jesus’ word — and they break with fish. Falling at His knees, Peter cries, “Depart from me; for I am a sinful man.” They leave everything and follow.",
    quote: "Follow me, and I will make you fishers of men.", qref: "Matthew 4:19" },
  { id: "synagogue-demoniac", act: 3, name: "The Man in the Synagogue", role: "Possessed by an unclean spirit", type: "healing", place: "Capernaum",
    refs: [["mk", "1:21–28"], ["lk", "4:31–37"]],
    text: "On the Sabbath a man cries out in the synagogue. With a word Jesus silences and expels the spirit, and His fame spreads through all Galilee.",
    quote: "Hold thy peace, and come out of him.", qref: "Mark 1:25" },
  { id: "peters-mother-in-law", act: 3, name: "Peter’s Mother-in-Law", role: "Lying sick with a great fever", type: "healing", place: "Capernaum",
    refs: [["mt", "8:14–15"], ["mk", "1:29–31"], ["lk", "4:38–39"]],
    text: "Jesus takes her by the hand and lifts her up; the fever leaves at once. That evening the whole city gathers at the door, and He heals many.",
    quote: "Immediately she arose and ministered unto them.", qref: "Luke 4:39" },
  { id: "leper", act: 3, name: "The Leper", role: "An outcast, full of leprosy", type: "healing", place: "A city of Galilee",
    refs: [["mt", "8:2–4"], ["mk", "1:40–45"], ["lk", "5:12–16"]],
    text: "Untouchable by law, he kneels and pleads. Moved with compassion, Jesus does the unthinkable — He reaches out and touches him.",
    quote: "I will; be thou clean.", qref: "Matthew 8:3" },
  { id: "paralytic", act: 3, name: "The Man Let Down Through the Roof", role: "A paralytic carried by four friends", type: "healing", place: "Capernaum",
    refs: [["mt", "9:2–8"], ["mk", "2:1–12"], ["lk", "5:17–26"]],
    text: "The house is too crowded, so his friends break open the roof and lower him down. Seeing their faith, Jesus first forgives his sins — then tells him to walk home.",
    quote: "Son, thy sins be forgiven thee… Arise, and take up thy bed, and go thy way.", qref: "Mark 2:5, 11" },
  { id: "matthew", act: 3, name: "Matthew (Levi)", role: "A tax collector", type: "encounter", place: "Capernaum", img: "matthew", feature: true,
    refs: [["mt", "9:9–13"], ["mk", "2:13–17"], ["lk", "5:27–32"]],
    text: "Despised as a collaborator with Rome, Matthew is sitting at the receipt of custom when Jesus says, “Follow me.” He rises, leaves all, and throws a feast for his fellow publicans and sinners.",
    quote: "They that be whole need not a physician, but they that are sick.", qref: "Matthew 9:12" },
  { id: "bethesda", act: 3, name: "The Man at Bethesda", role: "Infirm for thirty-eight years", type: "healing", place: "Pool of Bethesda, Jerusalem", img: "bethesda", feature: true,
    refs: [["jn", "5:1–15"]],
    text: "Among a great multitude of the blind, lame and withered, Jesus singles out one man who has no one to help him into the water. “Wilt thou be made whole?”",
    quote: "Rise, take up thy bed, and walk.", qref: "John 5:8" },
  { id: "withered-hand", act: 3, name: "The Man with the Withered Hand", role: "In the synagogue on the Sabbath", type: "healing", place: "Galilee",
    refs: [["mt", "12:9–14"], ["mk", "3:1–6"], ["lk", "6:6–11"]],
    text: "With His critics watching, Jesus asks whether it is lawful to do good on the Sabbath. Grieved at their hardness of heart, He speaks — and the hand is restored whole as the other.",
    quote: "Stretch forth thine hand.", qref: "Mark 3:5" },
  { id: "twelve", act: 3, name: "The Twelve", role: "Chosen to be with Him", type: "encounter", place: "A mountain in Galilee",
    refs: [["mk", "3:13–19"], ["lk", "6:12–16"], ["mt", "10:1–4"]],
    text: "After a night in prayer He names twelve: Simon Peter, Andrew, James and John, Philip, Bartholomew, Matthew, Thomas, James son of Alphaeus, Thaddaeus, Simon the Zealot — and Judas Iscariot.",
    quote: "He ordained twelve, that they should be with him, and that he might send them forth to preach.", qref: "Mark 3:14" },
  { id: "multitudes", act: 3, name: "The Multitudes on the Mount", role: "Disciples and crowds from every region", type: "teaching", place: "The Mount of Beatitudes", img: "sermon", feature: true,
    refs: [["mt", "5:1–7:29"], ["lk", "6:17–49"]],
    text: "The greatest sermon ever preached: the Beatitudes, salt and light, love for enemies, the Lord’s Prayer, the lilies of the field, the house upon the rock. The people are astonished — He teaches as one having authority.",
    quote: "Blessed are the pure in heart: for they shall see God.", qref: "Matthew 5:8" },
  { id: "centurion", act: 3, name: "The Centurion", role: "A Roman officer whose servant was dying", type: "healing", place: "Capernaum",
    refs: [["mt", "8:5–13"], ["lk", "7:1–10"]],
    text: "A Gentile soldier asks only for a word, understanding authority better than Israel’s teachers. Jesus marvels: “I have not found so great faith, no, not in Israel.”",
    quote: "Lord, I am not worthy that thou shouldest come under my roof: but speak the word only, and my servant shall be healed.", qref: "Matthew 8:8" },
  { id: "widow-nain", act: 3, name: "The Widow of Nain", role: "Burying her only son", type: "miracle", place: "Nain",
    refs: [["lk", "7:11–17"]],
    text: "At the city gate He meets a funeral procession. Seeing the mother, the Lord has compassion on her. He touches the bier, the bearers stand still, and the dead man sits up and begins to speak.",
    quote: "Weep not… Young man, I say unto thee, Arise.", qref: "Luke 7:13–14" },
  { id: "johns-disciples", act: 3, name: "The Messengers of John", role: "Sent from Herod’s prison", type: "encounter", place: "Galilee",
    refs: [["mt", "11:2–19"], ["lk", "7:18–35"]],
    text: "Imprisoned and perhaps doubting, John sends to ask, “Art thou he that should come?” Jesus answers not with a claim, but with evidence.",
    quote: "The blind receive their sight, and the lame walk, the lepers are cleansed, and the deaf hear, the dead are raised up.", qref: "Matthew 11:5" },
  { id: "sinful-woman", act: 3, name: "The Woman with the Alabaster Box", role: "A woman known as a sinner", type: "encounter", place: "House of Simon the Pharisee",
    refs: [["lk", "7:36–50"]],
    text: "Uninvited, she weeps at His feet, washing them with her tears and wiping them with her hair. To His scandalised host Jesus tells of two debtors, both forgiven — she loved much, for she was forgiven much.",
    quote: "Thy faith hath saved thee; go in peace.", qref: "Luke 7:50" },
  { id: "women-followers", act: 3, name: "Mary Magdalene, Joanna & Susanna", role: "Women who ministered of their substance", type: "healing", place: "Galilee",
    refs: [["lk", "8:1–3"], ["mk", "16:9"]],
    text: "Among those travelling with Him were women He had healed — Mary called Magdalene, out of whom went seven devils; Joanna, wife of Herod’s steward; Susanna, and many others who provided for Him.",
    quote: "And certain women, which had been healed of evil spirits and infirmities…", qref: "Luke 8:2" },
  { id: "blind-mute", act: 3, name: "The Blind and Mute Man", role: "Possessed with a devil", type: "healing", place: "Galilee",
    refs: [["mt", "12:22–30"], ["lk", "11:14–23"]],
    text: "He heals the man so that he both speaks and sees. The crowds wonder, “Is not this the son of David?” — while the Pharisees accuse Him of casting out devils by Beelzebub.",
    quote: "If I cast out devils by the Spirit of God, then the kingdom of God is come unto you.", qref: "Matthew 12:28" },
  { id: "family", act: 3, name: "His Mother and Brethren", role: "Standing outside the crowd", type: "teaching", place: "Galilee",
    refs: [["mt", "12:46–50"], ["mk", "3:31–35"], ["lk", "8:19–21"]],
    text: "Told that His family waits outside, Jesus stretches His hand toward His disciples and redefines what it means to belong to Him.",
    quote: "Whosoever shall do the will of my Father which is in heaven, the same is my brother, and sister, and mother.", qref: "Matthew 12:50" },
  { id: "storm", act: 3, name: "The Disciples in the Storm", role: "Terrified on the Sea of Galilee", type: "miracle", place: "The Sea of Galilee", img: "storm", feature: true,
    refs: [["mt", "8:23–27"], ["mk", "4:35–41"], ["lk", "8:22–25"]],
    text: "A great storm fills the boat with water while Jesus sleeps on a pillow in the stern. They wake Him — “Master, carest thou not that we perish?” He rebukes the wind, and there is a great calm.",
    quote: "Peace, be still.", qref: "Mark 4:39" },
  { id: "legion", act: 3, name: "Legion", role: "The Gadarene demoniac among the tombs", type: "healing", place: "Country of the Gadarenes",
    refs: [["mk", "5:1–20"], ["mt", "8:28–34"], ["lk", "8:26–39"]],
    text: "No chain could hold him; he cut himself with stones night and day. Jesus casts the legion of spirits into a herd of swine — and the man is found sitting, clothed, in his right mind. He becomes the first missionary to the Decapolis.",
    quote: "Go home to thy friends, and tell them how great things the Lord hath done for thee.", qref: "Mark 5:19" },
  { id: "bleeding-woman", act: 3, name: "The Woman Who Touched His Hem", role: "Twelve years with an issue of blood", type: "healing", place: "Capernaum",
    refs: [["mk", "5:25–34"], ["mt", "9:20–22"], ["lk", "8:43–48"]],
    text: "She had spent all she had on physicians and only grew worse. In the press of the crowd she touches His garment and is healed instantly. Jesus stops everything to find her — and calls her daughter.",
    quote: "Daughter, thy faith hath made thee whole; go in peace.", qref: "Mark 5:34" },
  { id: "jairus", act: 3, name: "Jairus’ Daughter", role: "Twelve years old, the ruler’s only daughter", type: "miracle", place: "Capernaum", img: "jairus", feature: true,
    refs: [["mk", "5:21–43"], ["mt", "9:18–26"], ["lk", "8:40–56"]],
    text: "News comes that the girl has died. “Be not afraid, only believe.” Putting the mourners out, Jesus takes her by the hand and speaks in Aramaic — and she rises and walks.",
    quote: "Talitha cumi… Damsel, I say unto thee, arise.", qref: "Mark 5:41" },
  { id: "two-blind", act: 3, name: "Two Blind Men", role: "Following Him, crying out", type: "healing", place: "Capernaum",
    refs: [["mt", "9:27–31"]],
    text: "“Believe ye that I am able to do this?” “Yea, Lord.” He touches their eyes, and they are opened.",
    quote: "According to your faith be it unto you.", qref: "Matthew 9:29" },
  { id: "mute-demoniac", act: 3, name: "The Mute Man", role: "Possessed with a devil", type: "healing", place: "Capernaum",
    refs: [["mt", "9:32–34"]],
    text: "When the devil is cast out, the dumb man speaks, and the multitudes marvel: “It was never so seen in Israel.”",
    quote: "It was never so seen in Israel.", qref: "Matthew 9:33" },

  // ── ACT V ─────────────────────────────────────────────
  { id: "loaves", act: 4, name: "The Boy with Five Loaves", role: "And a multitude of five thousand men", type: "miracle", place: "Near Bethsaida", img: "loaves", feature: true,
    refs: [["jn", "6:1–14"], ["mt", "14:13–21"], ["mk", "6:30–44"], ["lk", "9:10–17"]],
    text: "The only miracle recorded in all four Gospels. A boy offers his lunch; Jesus gives thanks and breaks it, and five thousand men — besides women and children — eat and are filled. Twelve baskets of fragments remain.",
    quote: "There is a lad here, which hath five barley loaves, and two small fishes: but what are they among so many?", qref: "John 6:9" },
  { id: "walk-water", act: 4, name: "Peter on the Water", role: "Stepping out of the boat", type: "miracle", place: "The Sea of Galilee", img: "walkwater", feature: true,
    refs: [["mt", "14:22–33"], ["mk", "6:45–52"], ["jn", "6:16–21"]],
    text: "In the fourth watch of the night, Jesus comes walking on the sea. Peter asks to come to Him and walks on the water — until he sees the wind and begins to sink. Immediately Jesus stretches out His hand.",
    quote: "Be of good cheer; it is I; be not afraid.", qref: "Matthew 14:27" },
  { id: "gennesaret", act: 4, name: "The Sick of Gennesaret", role: "Brought from all the region", type: "healing", place: "Gennesaret",
    refs: [["mt", "14:34–36"], ["mk", "6:53–56"]],
    text: "Wherever He enters — villages, cities, country — they lay the sick in the streets and beg to touch even the border of His garment.",
    quote: "As many as touched were made perfectly whole.", qref: "Matthew 14:36" },
  { id: "bread-of-life", act: 4, name: "The Crowd at Capernaum", role: "Seeking more bread", type: "teaching", place: "Synagogue of Capernaum",
    refs: [["jn", "6:22–71"]],
    text: "They want another meal; He offers Himself. Many turn back and walk no more with Him. Jesus asks the Twelve, “Will ye also go away?” Peter answers for them all.",
    quote: "Lord, to whom shall we go? thou hast the words of eternal life.", qref: "John 6:68" },
  { id: "syrophoenician", act: 4, name: "The Syrophoenician Woman", role: "A Gentile mother from Canaan", type: "healing", place: "Coasts of Tyre and Sidon",
    refs: [["mt", "15:21–28"], ["mk", "7:24–30"]],
    text: "She will not stop crying after Him for her tormented daughter. Tested, she answers with humble wit: even the dogs eat the crumbs from the master’s table. Her daughter is healed that very hour.",
    quote: "O woman, great is thy faith: be it unto thee even as thou wilt.", qref: "Matthew 15:28" },
  { id: "deaf-mute", act: 4, name: "The Deaf Man of Decapolis", role: "With an impediment in his speech", type: "healing", place: "The Decapolis",
    refs: [["mk", "7:31–37"]],
    text: "Jesus takes him aside from the multitude, puts His fingers in his ears, touches his tongue, looks up to heaven, and sighs.",
    quote: "Ephphatha, that is, Be opened.", qref: "Mark 7:34" },
  { id: "four-thousand", act: 4, name: "The Four Thousand", role: "Three days with Him in the wilderness", type: "miracle", place: "The Decapolis",
    refs: [["mt", "15:32–39"], ["mk", "8:1–10"]],
    text: "Moved with compassion for a hungry crowd far from home, He takes seven loaves and a few small fishes. All eat and are filled, and seven baskets remain.",
    quote: "I have compassion on the multitude.", qref: "Mark 8:2" },
  { id: "bethsaida-blind", act: 4, name: "The Blind Man of Bethsaida", role: "Healed in two touches", type: "healing", place: "Bethsaida",
    refs: [["mk", "8:22–26"]],
    text: "Jesus leads him by the hand out of town. After the first touch he sees dimly; after the second, he sees every man clearly — the only healing that happens in stages.",
    quote: "I see men as trees, walking.", qref: "Mark 8:24" },
  { id: "confession", act: 4, name: "Peter at Caesarea Philippi", role: "The great confession", type: "encounter", place: "Caesarea Philippi",
    refs: [["mt", "16:13–20"], ["mk", "8:27–30"], ["lk", "9:18–21"]],
    text: "“Whom say ye that I am?” Peter answers with a revelation not from flesh and blood. From this day Jesus begins to tell them plainly that He must suffer, die, and rise again.",
    quote: "Thou art the Christ, the Son of the living God.", qref: "Matthew 16:16" },
  { id: "transfiguration", act: 4, name: "Moses & Elijah", role: "On the holy mountain, with Peter, James and John", type: "miracle", place: "A high mountain", img: "transfig", feature: true,
    refs: [["mt", "17:1–8"], ["mk", "9:2–8"], ["lk", "9:28–36"]],
    text: "His face shines as the sun, His garments white as light. The Law and the Prophets appear, speaking with Him of His departure at Jerusalem. A bright cloud overshadows them, and the Father speaks.",
    quote: "This is my beloved Son, in whom I am well pleased; hear ye him.", qref: "Matthew 17:5" },
  { id: "epileptic-boy", act: 4, name: "The Father of the Afflicted Boy", role: "His only son, seized by a spirit", type: "healing", place: "Below the mountain",
    refs: [["mk", "9:14–29"], ["mt", "17:14–21"], ["lk", "9:37–43"]],
    text: "The disciples could not help. “If thou canst believe, all things are possible.” The father’s tearful cry becomes the prayer of every struggling believer.",
    quote: "Lord, I believe; help thou mine unbelief.", qref: "Mark 9:24" },
  { id: "coin-fish", act: 4, name: "Peter and the Temple Tax", role: "A coin in a fish’s mouth", type: "miracle", place: "Capernaum",
    refs: [["mt", "17:24–27"]],
    text: "Asked if his Master pays the temple tax, Peter is sent to cast a hook. The first fish he catches holds a piece of money — enough for them both.",
    quote: "Take that, and give unto them for me and thee.", qref: "Matthew 17:27" },
  { id: "little-child", act: 4, name: "The Little Child", role: "Set in the midst of the disciples", type: "teaching", place: "Capernaum",
    refs: [["mt", "18:1–5"], ["mk", "9:33–37"], ["lk", "9:46–48"]],
    text: "The disciples argue over who will be greatest. Jesus answers by calling a little child and setting him in the midst of them.",
    quote: "Except ye be converted, and become as little children, ye shall not enter into the kingdom of heaven.", qref: "Matthew 18:3" },

  // ── ACT VI ────────────────────────────────────────────
  { id: "sons-of-thunder", act: 5, name: "James & John", role: "The Sons of Thunder", type: "teaching", place: "A Samaritan village",
    refs: [["lk", "9:51–56"], ["mk", "3:17"]],
    text: "When a Samaritan village refuses Him, the brothers offer to call down fire from heaven. He turns and rebukes them.",
    quote: "The Son of man is not come to destroy men’s lives, but to save them.", qref: "Luke 9:56" },
  { id: "would-be", act: 5, name: "The Would-Be Followers", role: "Three who hesitated", type: "teaching", place: "On the road",
    refs: [["lk", "9:57–62"], ["mt", "8:19–22"]],
    text: "One promises to follow anywhere; another must first bury his father; another must first say farewell. Jesus is honest about the cost.",
    quote: "Foxes have holes, and birds of the air have nests; but the Son of man hath not where to lay his head.", qref: "Luke 9:58" },
  { id: "seventy", act: 5, name: "The Seventy", role: "Sent two by two", type: "encounter", place: "Every city and place",
    refs: [["lk", "10:1–24"]],
    text: "He sends seventy ahead of Him as lambs among wolves. They return with joy — even the devils are subject to them — and Jesus rejoices in spirit.",
    quote: "The harvest truly is great, but the labourers are few.", qref: "Luke 10:2" },
  { id: "lawyer", act: 5, name: "The Lawyer", role: "Asking, “Who is my neighbour?”", type: "teaching", place: "Judea",
    refs: [["lk", "10:25–37"]],
    text: "Seeking to justify himself, an expert in the Law receives a story: a man beaten on the Jericho road, passed by a priest and a Levite, rescued by a despised Samaritan.",
    quote: "Go, and do thou likewise.", qref: "Luke 10:37" },
  { id: "martha-mary", act: 5, name: "Martha & Mary", role: "Sisters of Bethany", type: "encounter", place: "Bethany",
    refs: [["lk", "10:38–42"]],
    text: "Martha is cumbered about much serving; Mary sits at the Lord’s feet and hears His word. Jesus speaks tenderly to the busy sister.",
    quote: "Mary hath chosen that good part, which shall not be taken away from her.", qref: "Luke 10:42" },
  { id: "adulteress", act: 5, name: "The Woman Taken in Adultery", role: "Dragged before Him at dawn", type: "encounter", place: "The Temple, Jerusalem",
    refs: [["jn", "8:1–11"]],
    text: "Her accusers demand a verdict. Jesus stoops and writes on the ground. One by one, beginning at the eldest, they drop their stones and leave — until only Jesus and the woman remain.",
    quote: "Neither do I condemn thee: go, and sin no more.", qref: "John 8:11" },
  { id: "man-born-blind", act: 5, name: "The Man Born Blind", role: "A beggar who had never seen", type: "healing", place: "Pool of Siloam, Jerusalem", img: "blind", feature: true,
    refs: [["jn", "9:1–41"]],
    text: "Jesus spits on the ground, makes clay, anoints his eyes, and sends him to wash. Interrogated and cast out by the Pharisees, the man cannot explain theology — only his testimony. Later Jesus finds him, and he worships.",
    quote: "One thing I know, that, whereas I was blind, now I see.", qref: "John 9:25" },
  { id: "bent-woman", act: 5, name: "The Woman Bent Double", role: "Bowed together for eighteen years", type: "healing", place: "A synagogue, on the Sabbath",
    refs: [["lk", "13:10–17"]],
    text: "She could in no wise lift herself up. Jesus calls her over, lays His hands on her, and immediately she is made straight and glorifies God.",
    quote: "Woman, thou art loosed from thine infirmity.", qref: "Luke 13:12" },
  { id: "dropsy", act: 5, name: "The Man with Dropsy", role: "At a chief Pharisee’s table", type: "healing", place: "A Pharisee’s house",
    refs: [["lk", "14:1–6"]],
    text: "Watched closely on the Sabbath, Jesus asks the lawyers a question they cannot answer — then takes the man, heals him, and lets him go.",
    quote: "Which of you shall have an ass or an ox fallen into a pit, and will not straightway pull him out on the sabbath day?", qref: "Luke 14:5" },
  { id: "sinners", act: 5, name: "The Publicans and Sinners", role: "Drawing near to hear Him", type: "teaching", place: "Perea", img: "prodigal", feature: true,
    refs: [["lk", "15:1–32"]],
    text: "The Pharisees murmur that He receives sinners and eats with them. He answers with three stories of lost things — a sheep, a coin, and a son — and a father who runs.",
    quote: "This my son was dead, and is alive again; he was lost, and is found.", qref: "Luke 15:24" },
  { id: "lazarus", act: 5, name: "Lazarus of Bethany", role: "Four days in the tomb", type: "miracle", place: "Bethany", img: "lazarus", feature: true,
    refs: [["jn", "11:1–44"]],
    text: "Jesus waits, and His friend dies. Martha meets Him with grief and faith; Mary falls at His feet. Jesus weeps. Then He stands before the tomb and cries with a loud voice — and the dead man comes forth, bound in grave clothes.",
    quote: "I am the resurrection, and the life: he that believeth in me, though he were dead, yet shall he live.", qref: "John 11:25" },
  { id: "ten-lepers", act: 5, name: "The Ten Lepers", role: "And the one Samaritan who returned", type: "healing", place: "Between Samaria and Galilee",
    refs: [["lk", "17:11–19"]],
    text: "Ten cry out from a distance; all ten are cleansed on their way to the priests. Only one — a foreigner — turns back, falls on his face, and gives thanks.",
    quote: "Were there not ten cleansed? but where are the nine?", qref: "Luke 17:17" },
  { id: "children", act: 5, name: "The Little Children", role: "Brought for His blessing", type: "encounter", place: "Perea", img: "children", feature: true,
    refs: [["mk", "10:13–16"], ["mt", "19:13–15"], ["lk", "18:15–17"]],
    text: "The disciples rebuke the parents. Jesus is much displeased — and takes the children up in His arms, puts His hands upon them, and blesses them.",
    quote: "Suffer the little children to come unto me, and forbid them not: for of such is the kingdom of God.", qref: "Mark 10:14" },
  { id: "rich-ruler", act: 5, name: "The Rich Young Ruler", role: "Who kept every commandment", type: "teaching", place: "Perea", img: "richruler", feature: true,
    refs: [["mk", "10:17–31"], ["mt", "19:16–30"], ["lk", "18:18–30"]],
    text: "He runs, kneels, and asks what he must do to inherit eternal life. Jesus, beholding him, loves him — and asks for the one thing he cannot give. He goes away grieved, for he had great possessions.",
    quote: "With men this is impossible; but with God all things are possible.", qref: "Matthew 19:26" },
  { id: "salome", act: 5, name: "The Mother of Zebedee’s Children", role: "Asking thrones for her sons", type: "teaching", place: "On the road to Jerusalem",
    refs: [["mt", "20:20–28"], ["mk", "10:35–45"]],
    text: "She asks that James and John sit at His right and left hand in His kingdom. Jesus answers by redefining greatness itself.",
    quote: "The Son of man came not to be ministered unto, but to minister, and to give his life a ransom for many.", qref: "Matthew 20:28" },
  { id: "bartimaeus", act: 5, name: "Blind Bartimaeus", role: "Son of Timaeus, begging by the wayside", type: "healing", place: "Jericho",
    refs: [["mk", "10:46–52"], ["mt", "20:29–34"], ["lk", "18:35–43"]],
    text: "Told to be quiet, he cries out all the more. Jesus stands still and calls for him. Casting away his garment, he comes — and follows Jesus in the way.",
    quote: "Jesus, thou son of David, have mercy on me… Go thy way; thy faith hath made thee whole.", qref: "Mark 10:47, 52" },
  { id: "zacchaeus", act: 5, name: "Zacchaeus", role: "Chief among the publicans, and rich", type: "encounter", place: "Jericho", img: "zacchaeus", feature: true,
    refs: [["lk", "19:1–10"]],
    text: "Too short to see over the crowd, he climbs a sycamore tree. Jesus stops beneath it, calls him by name, and invites Himself to dinner. Zacchaeus gives half his goods to the poor and restores fourfold.",
    quote: "For the Son of man is come to seek and to save that which was lost.", qref: "Luke 19:10" },

  // ── ACT VII ───────────────────────────────────────────
  { id: "mary-anoints", act: 6, name: "Mary of Bethany", role: "With a pound of costly spikenard", type: "encounter", place: "Bethany",
    refs: [["jn", "12:1–8"], ["mt", "26:6–13"], ["mk", "14:3–9"]],
    text: "Six days before Passover she breaks the box and pours the ointment on Him, and the house is filled with its fragrance. Judas objects to the waste. Jesus says she has anointed Him for His burial.",
    quote: "She hath wrought a good work on me.", qref: "Mark 14:6" },
  { id: "triumphal", act: 6, name: "The Crowds of Jerusalem", role: "With palm branches and garments", type: "encounter", place: "The Mount of Olives → Jerusalem", img: "entry", feature: true,
    refs: [["mk", "11:1–11"], ["mt", "21:1–11"], ["lk", "19:28–44"], ["jn", "12:12–19"]],
    text: "He rides into the city on a borrowed colt, fulfilling Zechariah’s prophecy, as the multitudes spread their garments in the way. Yet when He beholds the city, He weeps over it.",
    quote: "Hosanna; Blessed is he that cometh in the name of the Lord.", qref: "Mark 11:9" },
  { id: "fig-tree", act: 6, name: "The Barren Fig Tree", role: "Leaves, but no fruit", type: "miracle", place: "Bethany road",
    refs: [["mk", "11:12–14, 20–25"], ["mt", "21:18–22"]],
    text: "A living parable. The tree He curses is found withered from the roots, and He teaches His disciples about faith and forgiveness in prayer.",
    quote: "Have faith in God.", qref: "Mark 11:22" },
  { id: "temple", act: 6, name: "The Blind and Lame in the Temple", role: "After the tables were overturned", type: "healing", place: "The Temple, Jerusalem", img: "temple", feature: true,
    refs: [["mt", "21:12–17"], ["mk", "11:15–19"], ["lk", "19:45–48"]],
    text: "Again He drives out the buyers and sellers. Then, in the cleared courts, the blind and the lame come to Him and He heals them, while children cry, “Hosanna to the son of David.”",
    quote: "My house shall be called the house of prayer.", qref: "Matthew 21:13" },
  { id: "greeks", act: 6, name: "The Greeks", role: "Gentiles come up to worship at the feast", type: "teaching", place: "Jerusalem",
    refs: [["jn", "12:20–36"]],
    text: "Through Philip and Andrew they make a simple request. Jesus answers that the hour has come — and speaks of a grain of wheat.",
    quote: "Sir, we would see Jesus.", qref: "John 12:21" },
  { id: "caesar", act: 6, name: "The Pharisees & Herodians", role: "Laying a trap", type: "teaching", place: "The Temple courts",
    refs: [["mt", "22:15–22"], ["mk", "12:13–17"], ["lk", "20:20–26"]],
    text: "“Is it lawful to give tribute unto Caesar?” He asks for a penny and whose image it bears. They marvel and leave Him.",
    quote: "Render therefore unto Caesar the things which are Caesar’s; and unto God the things that are God’s.", qref: "Matthew 22:21" },
  { id: "scribe", act: 6, name: "The Scribe", role: "Asking the first commandment of all", type: "teaching", place: "The Temple courts",
    refs: [["mk", "12:28–34"], ["mt", "22:34–40"]],
    text: "Love God with all thy heart, soul, mind and strength; love thy neighbour as thyself. The scribe answers discreetly, and Jesus tells him the most hopeful thing.",
    quote: "Thou art not far from the kingdom of God.", qref: "Mark 12:34" },
  { id: "widow-mites", act: 6, name: "The Poor Widow", role: "With two mites", type: "encounter", place: "The Temple treasury",
    refs: [["mk", "12:41–44"], ["lk", "21:1–4"]],
    text: "The rich cast in much. She casts in two small coins — all her living. Jesus calls His disciples to see what heaven sees.",
    quote: "This poor widow hath cast more in, than all they which have cast into the treasury.", qref: "Mark 12:43" },
  { id: "judas", act: 6, name: "Judas Iscariot", role: "One of the Twelve", type: "encounter", place: "Jerusalem",
    refs: [["mt", "26:14–16, 20–25"], ["mk", "14:10–11"], ["lk", "22:3–6"], ["jn", "13:21–30"]],
    text: "He covenants with the chief priests for thirty pieces of silver. At the table Jesus gives him the sop; Judas goes out immediately — “and it was night.”",
    quote: "Verily I say unto you, that one of you shall betray me.", qref: "Matthew 26:21" },
  { id: "feet", act: 6, name: "Peter at the Basin", role: "Refusing, then asking for more", type: "teaching", place: "The Upper Room", img: "feet", feature: true,
    refs: [["jn", "13:1–17"]],
    text: "Knowing the Father had given all things into His hands, the Lord rises, girds Himself with a towel, and washes His disciples’ feet. Peter protests: “Thou shalt never wash my feet.”",
    quote: "If I wash thee not, thou hast no part with me.", qref: "John 13:8" },
  { id: "last-supper", act: 6, name: "The Twelve at Table", role: "The Passover meal", type: "teaching", place: "The Upper Room", img: "supper", feature: true,
    refs: [["lk", "22:7–38"], ["mt", "26:17–30"], ["mk", "14:12–26"], ["jn", "13:31–35"]],
    text: "He takes bread, gives thanks, breaks it; then the cup — the new testament in His blood. He gives them a new commandment, and they sing a hymn and go out to the Mount of Olives.",
    quote: "This is my body which is given for you: this do in remembrance of me.", qref: "Luke 22:19" },
  { id: "thomas-philip", act: 6, name: "Thomas & Philip", role: "Asking the way", type: "teaching", place: "The Upper Room",
    refs: [["jn", "14:1–31"]],
    text: "“Lord, we know not whither thou goest; and how can we know the way?” “Lord, shew us the Father.” The answers are among the most comforting words ever spoken.",
    quote: "I am the way, the truth, and the life: no man cometh unto the Father, but by me.", qref: "John 14:6" },

  // ── ACT VIII ──────────────────────────────────────────
  { id: "gethsemane", act: 7, name: "Peter, James & John", role: "Asleep in the garden", type: "encounter", place: "Gethsemane", img: "gethsemane", feature: true,
    refs: [["mt", "26:36–46"], ["mk", "14:32–42"], ["lk", "22:39–46"]],
    text: "Exceeding sorrowful unto death, He falls on His face and prays three times. His sweat is as great drops of blood; an angel appears to strengthen Him. Three times He returns to find His friends asleep.",
    quote: "Nevertheless not my will, but thine, be done.", qref: "Luke 22:42" },
  { id: "judas-kiss", act: 7, name: "Judas’ Kiss", role: "With a band of soldiers and officers", type: "encounter", place: "Gethsemane", img: "taking", feature: true,
    refs: [["lk", "22:47–48"], ["mt", "26:47–56"], ["mk", "14:43–50"], ["jn", "18:1–9"]],
    text: "The sign agreed upon is a kiss. When Jesus says “I am he,” the soldiers go backward and fall to the ground. He asks only that His disciples be let go. Then all forsake Him and flee.",
    quote: "Judas, betrayest thou the Son of man with a kiss?", qref: "Luke 22:48" },
  { id: "malchus", act: 7, name: "Malchus", role: "Servant of the high priest", type: "healing", place: "Gethsemane",
    refs: [["lk", "22:49–51"], ["jn", "18:10–11"], ["mt", "26:51–54"], ["mk", "14:47"]],
    text: "Peter draws a sword and cuts off his right ear. In the moment of His arrest, Jesus heals an enemy — His last miracle of healing before the cross.",
    quote: "And he touched his ear, and healed him.", qref: "Luke 22:51" },
  { id: "young-man", act: 7, name: "The Young Man Who Fled", role: "Wearing only a linen cloth", type: "encounter", place: "Gethsemane",
    refs: [["mk", "14:51–52"]],
    text: "Recorded only by Mark: a young man follows, is seized, and escapes naked, leaving the linen behind. Many believe it was Mark himself.",
    quote: "He left the linen cloth, and fled from them naked.", qref: "Mark 14:52" },
  { id: "annas", act: 7, name: "Annas", role: "Former high priest, father-in-law of Caiaphas", type: "encounter", place: "The house of Annas",
    refs: [["jn", "18:12–24"]],
    text: "Questioned by night about His disciples and doctrine, Jesus replies that He spoke openly to the world. An officer strikes Him with the palm of his hand.",
    quote: "If I have spoken well, why smitest thou me?", qref: "John 18:23" },
  { id: "caiaphas", act: 7, name: "Caiaphas & the Council", role: "High priest that same year", type: "encounter", place: "Palace of the high priest",
    refs: [["mk", "14:53–65"], ["mt", "26:57–68"], ["lk", "22:66–71"]],
    text: "False witnesses cannot agree. Finally the high priest asks Him directly — and Jesus answers. They condemn Him as guilty of death, spit in His face, and buffet Him.",
    quote: "Art thou the Christ, the Son of the Blessed? And Jesus said, I am.", qref: "Mark 14:61–62" },
  { id: "denial", act: 7, name: "Peter by the Fire", role: "Questioned by a servant girl", type: "encounter", place: "The high priest’s courtyard", img: "denial", feature: true,
    refs: [["lk", "22:54–62"], ["mt", "26:69–75"], ["mk", "14:66–72"], ["jn", "18:15–27"]],
    text: "Three times he denies knowing Him. Then the cock crows — and the Lord turns and looks upon Peter. He goes out and weeps bitterly.",
    quote: "And the Lord turned, and looked upon Peter.", qref: "Luke 22:61" },
  { id: "judas-remorse", act: 7, name: "Judas’ Remorse", role: "Returning the silver", type: "encounter", place: "The Temple",
    refs: [["mt", "27:3–10"]],
    text: "Seeing Jesus condemned, Judas brings back the thirty pieces, confessing he has betrayed innocent blood. The priests buy a potter’s field with it.",
    quote: "I have sinned in that I have betrayed the innocent blood.", qref: "Matthew 27:4" },
  { id: "pilate", act: 7, name: "Pontius Pilate", role: "Roman governor of Judea", type: "encounter", place: "The Praetorium", img: "truth", feature: true,
    refs: [["jn", "18:28–19:16"], ["mt", "27:11–26"], ["mk", "15:1–15"], ["lk", "23:1–25"]],
    text: "“Art thou the King of the Jews?” Jesus answers that His kingdom is not of this world, and that He came to bear witness to the truth. Pilate finds no fault in Him — and washes his hands.",
    quote: "Pilate saith unto him, What is truth?", qref: "John 18:38" },
  { id: "herod-antipas", act: 7, name: "Herod Antipas", role: "Tetrarch of Galilee", type: "encounter", place: "Jerusalem",
    refs: [["lk", "23:6–12"]],
    text: "Hoping to see a miracle, Herod questions Him at length. Jesus answers him nothing. Herod and his soldiers mock Him, array Him in a gorgeous robe, and send Him back to Pilate.",
    quote: "He questioned with him in many words; but he answered him nothing.", qref: "Luke 23:9" },
  { id: "pilates-wife", act: 7, name: "Pilate’s Wife", role: "Troubled by a dream", type: "encounter", place: "The Praetorium",
    refs: [["mt", "27:19"]],
    text: "While her husband sits on the judgment seat, she sends an urgent message.",
    quote: "Have thou nothing to do with that just man: for I have suffered many things this day in a dream because of him.", qref: "Matthew 27:19" },
  { id: "barabbas", act: 7, name: "Barabbas", role: "A notable prisoner, guilty of insurrection and murder", type: "encounter", place: "The Praetorium",
    refs: [["mt", "27:15–26"], ["mk", "15:6–15"], ["lk", "23:18–25"], ["jn", "18:39–40"]],
    text: "Offered a choice at the feast, the crowd chooses the guilty man. Barabbas walks free, and the innocent One dies in the place of the guilty.",
    quote: "Not this man, but Barabbas.", qref: "John 18:40" },
  { id: "soldiers", act: 7, name: "The Soldiers", role: "The whole band of the Praetorium", type: "encounter", place: "The common hall", img: "eccehomo", feature: true,
    refs: [["jn", "19:1–5"], ["mt", "27:27–31"], ["mk", "15:16–20"]],
    text: "He is scourged. They plait a crown of thorns, put a purple robe on Him, and bow in mockery. Then Pilate brings Him out before the people.",
    quote: "Behold the man!", qref: "John 19:5" },
  { id: "simon-cyrene", act: 7, name: "Simon of Cyrene", role: "Father of Alexander and Rufus", type: "encounter", place: "The Via Dolorosa", img: "cyrene", feature: true,
    refs: [["mk", "15:21"], ["mt", "27:32"], ["lk", "23:26"]],
    text: "A man coming in from the country is compelled to carry the cross behind Jesus. Mark names his sons, as though his readers knew them well — the carrying may have changed his family forever.",
    quote: "On him they laid the cross, that he might bear it after Jesus.", qref: "Luke 23:26" },
  { id: "daughters", act: 7, name: "The Daughters of Jerusalem", role: "Bewailing and lamenting Him", type: "encounter", place: "The way to Golgotha",
    refs: [["lk", "23:27–31"]],
    text: "Even on the way to His death, His concern is for others.",
    quote: "Daughters of Jerusalem, weep not for me, but weep for yourselves, and for your children.", qref: "Luke 23:28" },
  { id: "thief", act: 7, name: "The Thief on the Cross", role: "Crucified beside Him", type: "encounter", place: "Golgotha", img: "crossview", feature: true,
    refs: [["lk", "23:32–43"], ["mt", "27:38, 44"], ["mk", "15:27–32"]],
    text: "One criminal rails on Him. The other rebukes his companion and makes a simple request: “Lord, remember me when thou comest into thy kingdom.” He is the last person Jesus saves before He dies.",
    quote: "Verily I say unto thee, To day shalt thou be with me in paradise.", qref: "Luke 23:43" },
  { id: "mary-cross", act: 7, name: "His Mother & the Beloved Disciple", role: "Standing by the cross", type: "encounter", place: "Golgotha",
    refs: [["jn", "19:25–27"]],
    text: "Simeon’s sword has reached her soul. From the cross Jesus entrusts His mother to John, and from that hour the disciple takes her unto his own home.",
    quote: "Woman, behold thy son!… Behold thy mother!", qref: "John 19:26–27" },
  { id: "centurion-cross", act: 7, name: "The Centurion at the Cross", role: "Who stood over against Him", type: "encounter", place: "Golgotha",
    refs: [["mk", "15:39"], ["mt", "27:54"], ["lk", "23:47"]],
    text: "Seeing how He cried out and gave up the ghost, the Roman officer in charge of the execution becomes the first to confess Him after His death.",
    quote: "Truly this man was the Son of God.", qref: "Mark 15:39" },
  { id: "women-watching", act: 7, name: "The Women Who Watched", role: "Mary Magdalene, Mary the mother of James, Salome", type: "encounter", place: "Golgotha",
    refs: [["mk", "15:40–41"], ["mt", "27:55–56"], ["lk", "23:49"]],
    text: "When the men had fled, the women stayed — beholding afar off, and afterward marking where He was laid.",
    quote: "There were also women looking on afar off.", qref: "Mark 15:40" },
  { id: "burial", act: 7, name: "Joseph of Arimathea & Nicodemus", role: "Secret disciples, made bold", type: "encounter", place: "A new tomb in a garden", img: "entomb", feature: true,
    refs: [["jn", "19:38–42"], ["mt", "27:57–61"], ["mk", "15:42–47"], ["lk", "23:50–56"]],
    text: "A rich counsellor begs Pilate for the body. Nicodemus — who first came by night — brings a hundred pound weight of myrrh and aloes. They wrap Him in linen and lay Him in a tomb where never man was laid. A great stone is rolled to the door.",
    quote: "There laid they Jesus.", qref: "John 19:42" },

  // ── ACT IX ────────────────────────────────────────────
  { id: "angel-women", act: 8, name: "The Women at the Tomb", role: "Bringing spices at dawn", type: "miracle", place: "The Garden Tomb", img: "resurrection", feature: true,
    refs: [["mt", "28:1–10"], ["mk", "16:1–8"], ["lk", "24:1–12"]],
    text: "Very early, as it begins to dawn, they wonder who will roll away the stone. There is a great earthquake. An angel sits upon the stone, his countenance like lightning — and speaks the words that changed the world.",
    quote: "He is not here: for he is risen, as he said.", qref: "Matthew 28:6" },
  { id: "peter-john-run", act: 8, name: "Peter & John", role: "Running to the sepulchre", type: "encounter", place: "The Garden Tomb", img: "running", feature: true,
    refs: [["jn", "20:1–10"], ["lk", "24:12"]],
    text: "They run together; John outruns Peter. Inside, the linen clothes lie in their place, and the napkin that was about His head folded by itself. The other disciple sees — and believes.",
    quote: "So they ran both together.", qref: "John 20:4" },
  { id: "magdalene", act: 8, name: "Mary Magdalene", role: "Weeping in the garden", type: "encounter", place: "The Garden Tomb", img: "magdalene", feature: true,
    refs: [["jn", "20:11–18"], ["mk", "16:9"]],
    text: "She thinks He is the gardener — until He speaks her name. The first person to see the risen Lord is a woman once possessed by seven devils, sent as the apostle to the apostles.",
    quote: "Jesus saith unto her, Mary. She turned herself, and saith unto him, Rabboni.", qref: "John 20:16" },
  { id: "emmaus", act: 8, name: "Cleopas & His Companion", role: "Walking to Emmaus", type: "encounter", place: "The road to Emmaus", img: "emmaus", feature: true,
    refs: [["lk", "24:13–35"], ["mk", "16:12–13"]],
    text: "A stranger joins them on the road and opens the Scriptures, beginning at Moses. At supper He takes bread, blesses and breaks it — and their eyes are opened. He vanishes from their sight.",
    quote: "Did not our heart burn within us, while he talked with us by the way?", qref: "Luke 24:32" },
  { id: "upper-room", act: 8, name: "The Disciples Behind Closed Doors", role: "Assembled for fear", type: "encounter", place: "Jerusalem",
    refs: [["jn", "20:19–23"], ["lk", "24:36–49"]],
    text: "The doors are shut, yet Jesus stands in the midst. He shows them His hands and side, eats broiled fish before them, and breathes on them the Holy Ghost.",
    quote: "Peace be unto you: as my Father hath sent me, even so send I you.", qref: "John 20:21" },
  { id: "thomas", act: 8, name: "Thomas", role: "Called Didymus, the Twin", type: "encounter", place: "Jerusalem", img: "thomas", feature: true,
    refs: [["jn", "20:24–29"]],
    text: "“Except I shall see in his hands the print of the nails… I will not believe.” Eight days later, Jesus invites him to reach out his hand. The doubter makes the highest confession in the Gospels.",
    quote: "My Lord and my God.", qref: "John 20:28" },
  { id: "153-fish", act: 8, name: "Seven Disciples at Dawn", role: "Fishing all night, catching nothing", type: "miracle", place: "The Sea of Tiberias",
    refs: [["jn", "21:1–14"]],
    text: "A figure on the shore tells them where to cast. The net fills with a hundred and fifty-three great fish, yet is not broken. “It is the Lord!” Peter plunges into the sea. Breakfast is waiting on a fire of coals. His last recorded miracle.",
    quote: "Cast the net on the right side of the ship, and ye shall find.", qref: "John 21:6" },
  { id: "peter-restored", act: 8, name: "Peter Restored", role: "Beside a fire of coals", type: "encounter", place: "The Sea of Tiberias",
    refs: [["jn", "21:15–19"]],
    text: "Beside another charcoal fire, three questions answer three denials. Grieved, Peter says, “Lord, thou knowest all things; thou knowest that I love thee.”",
    quote: "Feed my sheep.", qref: "John 21:17" },
  { id: "beloved-disciple", act: 8, name: "The Beloved Disciple", role: "Who leaned on His breast at supper", type: "encounter", place: "The Sea of Tiberias",
    refs: [["jn", "21:20–25"]],
    text: "Peter asks what will happen to John. Jesus’ answer is for every disciple who has ever compared their path to another’s.",
    quote: "What is that to thee? follow thou me.", qref: "John 21:22" },
  { id: "commission", act: 8, name: "The Eleven on the Mountain", role: "Some worshipped; some doubted", type: "teaching", place: "A mountain in Galilee",
    refs: [["mt", "28:16–20"], ["mk", "16:15–18"]],
    text: "All power is given unto Him in heaven and in earth. He sends them to make disciples of all nations — with a promise that has never expired.",
    quote: "Lo, I am with you alway, even unto the end of the world.", qref: "Matthew 28:20" },
  { id: "ascension", act: 8, name: "The Witnesses of the Ascension", role: "Gazing up into heaven", type: "miracle", place: "Bethany · Mount Olivet", img: "ascension", feature: true,
    refs: [["lk", "24:50–53"], ["mk", "16:19–20"], ["acts", "1:9–11"]],
    text: "He leads them out as far as Bethany, lifts up His hands, and blesses them. While He blesses them, He is parted from them and a cloud receives Him. Two men in white apparel promise He will come again in like manner. They return to Jerusalem with great joy.",
    quote: "While he blessed them, he was parted from them, and carried up into heaven.", qref: "Luke 24:51" }
];

/*
 * One painting per encounter (keys into window.ART). No painting appears twice in
 * the story: act openers and interludes each use their own.
 */
window.ENC_ART = {
  zechariah: "t-zacharias", mary: "annunciation", elizabeth: "t-visitation", joseph: "t-joseph",
  shepherds: "t-shepherds", simeon: "t-presentation", anna: "anna", magi: "magi", herod: "t-innocents",
  teachers: "t-doctors",
  "john-baptist": "t-baptism", tempter: "t-tempted", andrew: "t-john-andrew", peter: "t-peter-andrew",
  philip: "t-philip", nathanael: "t-nathanael",
  cana: "cana", "moneychangers-1": "t-merchants", nicodemus: "nicodemus", "samaritan-woman": "well",
  nobleman: "t-officer",
  nazareth: "t-unrolls", fishermen: "fishes", "synagogue-demoniac": "t-possessed",
  "peters-mother-in-law": "t-mother-in-law", leper: "t-lepers-cap", paralytic: "t-palsied", matthew: "matthew",
  bethesda: "bethesda", "withered-hand": "t-withered", twelve: "t-twelve", multitudes: "t-beatitudes",
  centurion: "t-worthy", "widow-nain": "t-nain", "johns-disciples": "t-heals-lame", "sinful-woman": "t-pharisee-meal",
  "women-followers": "t-women-galilee", "blind-mute": "t-blind-mute", family: "t-discourses", storm: "t-tempest",
  legion: "t-legion", "bleeding-woman": "t-issue", jairus: "jairus", "two-blind": "t-blind-cap", "mute-demoniac": "t-mute",
  loaves: "loaves", "walk-water": "walkwater", gennesaret: "t-villages", "bread-of-life": "t-follow-miracles",
  syrophoenician: "t-canaanite", "deaf-mute": "t-sick-awaiting", "four-thousand": "t-mountain",
  "bethsaida-blind": "greco-blind", confession: "t-primacy", transfiguration: "transbloch", "epileptic-boy": "t-thabor",
  "coin-fish": "masaccio", "little-child": "t-little-child",
  "sons-of-thunder": "t-villages-way", "would-be": "t-traveling", seventy: "t-two-by-two", lawyer: "t-samaritan",
  "martha-mary": "vermeer", adulteress: "t-adulteress", "man-born-blind": "blind", "bent-woman": "t-eighteen",
  dropsy: "t-pharisees-q", sinners: "prodigal", lazarus: "lazarus", "ten-lepers": "t-ten-lepers", children: "children",
  "rich-ruler": "t-sorrowful", salome: "t-first-last", bartimaeus: "t-jericho", zacchaeus: "zacchaeus",
  "mary-anoints": "t-ointment", triumphal: "entry", "fig-tree": "t-fig", temple: "temple", greeks: "t-gentiles",
  caesar: "titian-tribute", scribe: "t-scribe", "widow-mites": "t-mite", judas: "t-judas-goes", feet: "t-feet",
  "last-supper": "t-supper", "thomas-philip": "t-philip-address",
  gethsemane: "gethsemane", "judas-kiss": "taking", malchus: "t-malchus", "young-man": "t-flight-apostles",
  annas: "t-annas", caiaphas: "t-false-witnesses", denial: "denial", "judas-remorse": "t-judas-returns",
  pilate: "truth", "herod-antipas": "t-herod", "pilates-wife": "t-pilates-wife", barabbas: "t-barabbas",
  soldiers: "thorns", "simon-cyrene": "cyrene", daughters: "t-daughters", thief: "t-good-thief",
  "mary-cross": "t-behold-son", "centurion-cross": "t-centurion-conf", "women-watching": "t-watch-afar", burial: "entomb",
  "angel-women": "resurrection", "peter-john-run": "running", magdalene: "magdalene", emmaus: "emmaus",
  "upper-room": "t-cenacle", thomas: "thomas", "153-fish": "t-draught2", "peter-restored": "t-feed-lambs",
  "beloved-disciple": "t-shore", commission: "t-exhortation", ascension: "ascension"
};

window.LAST_WORDS = [
  { t: "Father, forgive them; for they know not what they do.", r: "Luke 23:34" },
  { t: "To day shalt thou be with me in paradise.", r: "Luke 23:43" },
  { t: "Woman, behold thy son! … Behold thy mother!", r: "John 19:26–27" },
  { t: "Eli, Eli, lama sabachthani? — My God, my God, why hast thou forsaken me?", r: "Matthew 27:46" },
  { t: "I thirst.", r: "John 19:28" },
  { t: "It is finished.", r: "John 19:30" },
  { t: "Father, into thy hands I commend my spirit.", r: "Luke 23:46" }
];

window.I_AM = [
  { t: "the bread of life", r: "John 6:35", line: "He that cometh to me shall never hunger." },
  { t: "the light of the world", r: "John 8:12", line: "He that followeth me shall not walk in darkness." },
  { t: "the door", r: "John 10:9", line: "By me if any man enter in, he shall be saved." },
  { t: "the good shepherd", r: "John 10:11", line: "The good shepherd giveth his life for the sheep." },
  { t: "the resurrection, and the life", r: "John 11:25", line: "He that believeth in me, though he were dead, yet shall he live." },
  { t: "the way, the truth, and the life", r: "John 14:6", line: "No man cometh unto the Father, but by me." },
  { t: "the true vine", r: "John 15:1", line: "I am the vine, ye are the branches." }
];

window.PARABLES = [
  "The Sower", "The Mustard Seed", "The Good Samaritan", "The Prodigal Son", "The Lost Sheep", "The Lost Coin",
  "The Pearl of Great Price", "The Hidden Treasure", "The Wise and Foolish Builders", "The Ten Virgins",
  "The Talents", "The Unforgiving Servant", "The Labourers in the Vineyard", "The Rich Fool",
  "The Pharisee and the Publican", "The Persistent Widow", "The Wedding Feast", "The Wheat and the Tares",
  "The Leaven", "The Dragnet", "The Two Sons", "The Wicked Husbandmen", "The Sheep and the Goats",
  "The Lamp under a Bushel", "The Barren Fig Tree", "The Great Supper", "The Rich Man and Lazarus",
  "The Friend at Midnight", "The Unjust Steward", "The Seed Growing Secretly", "New Wine in Old Bottles",
  "The Two Debtors", "The Unprofitable Servants", "The Faithful Servant"
];
